[project]
name = "clipper"
version = "0.1.0"
dependencies = [
  "pick",
  "Pygments",
  "pyperclip",
  "PyYAML",
  "regex"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["clipper"]

[project.scripts]
clipper = "clipper.cli:main"