from pathlib import Path
import json
import re
import urllib.request
import pprint


LEXER_RE = re.compile(r"^([^\[]+)\[(.+)\]\s*\n?$")

SOURCE_URL = "https://raw.githubusercontent.com/ttscoff/snibbets/master/lib/snibbets/lexers_db.rb"
TARGET_FILE = Path(__file__).parent.parent / "clipper" / "language_data.py"

HEADER = """### DO NOT EDIT THIS FILE
### This file was autogenerated using data from:
### https://github.com/ttscoff/snibbets/blob/master/lib/snibbets/lexers_db.rb
###
"""


def parse_lexer_line(line):
    m = LEXER_RE.search(line)
    if not m:
        return None
    langs = [l.strip() for l in m.group(1).split(",")]
    exts = [e.strip() for e in m.group(2).split(",")]
    return {"lang": langs[0], "aliases": [l.lower() for l in langs[1:]], "exts": exts}


### Not used currently
def __parse_lexer_data(lines: list[str]):
    in_lexers = False
    data = []
    for line in lines:
        if line == "LEXERS_DB =<<EOLEXERS":
            in_lexers = True
        elif line == "EOLEXERS":
            return data
        elif in_lexers:
            lexer = parse_lexer_line(line)
            if lexer:
                data.append(lexer)


file_lines = []
with urllib.request.urlopen(SOURCE_URL) as f:
    file_lines = f.read().decode("utf-8").split("\n")

data = __parse_lexer_data(file_lines)

with open(TARGET_FILE, "w") as f:
    print(f"{HEADER}\n\nLANGUAGES = {pprint.pformat(data, compact=True)}", file=f)
