import re
import json

LEXER_RE = re.compile(r"^([^\[]+)\[(.+)\]\s*\n?$")

SOURCE_URL = "https://github.com/ttscoff/snibbets/blob/master/lib/snibbets/lexers_db.rb"

HEADER = f"""
### This file was autogenerated using data from:
### {SOURCE_URL}
###
"""


def parse_lexer_line(line):
    m = LEXER_RE.search(line)
    if not m:
        return None
    langs = [l.strip() for l in m.group(1).split(",")]
    exts = [e.strip() for e in m.group(2).split(",")]
    return {"lang": langs[0], "aliases": [l.lower() for l in langs[1:]], "exts": exts}


### Not used currently
def __parse_lexer_data(lines: list[str]):
    in_lexers = False
    data = []
    for line in lines:
        if line == "LEXERS_DB =<<EOLEXERS":
            in_lexers = True
        elif line == "EOLEXERS":
            return data
        elif in_lexers:
            lexer = parse_lexer_line(line)
            if lexer:
                data.append(lexer)


data = []
with open("exts.txt") as f:
    for line in f.readlines():
        lang = parse_lexer_line(line)
        if lang:
            data.append(lang)

with open("langauge_data.py", "w") as f:
    print(f"{HEADER}\n\nLANGUAGES = {json.dumps(data)}", file=f)
